GET http://localhost:3003/turma

###

POST http://localhost:3003/turma
Content-Type: application/json

{
    "nome": "Hopper",
    "modulo": "1"
}

###

PUT http://localhost:3003/turma/modulo
Content-Type: application/json

{
    "id": "1664923146588",
    "modulo": "3"
}