export const TABELA_TURMA = "LabeSys_Turma"
export const TABELA_ESTUDANTE = "LabeSys_Estudante"
export const TABELA_DOCENTE = "LabeSys_Docente"
export const TABELA_HOBBY = "LabeSys_Hobby"
export const TABELA_ESPECIALIDADE = "LabeSys_Especialidade"
export const TABELA_ESTUDANTE_HOBBY = "LabeSys_Estudante_Hobby"
export const TABELA_DOCENTE_ESPECIALIDADE = "LabeSys_Docente_Especialidade"